Repository intake/intake-esm, pull requests merged in 2021-12, with the labels that each got.

#395 Added detection of "*" to enable opening of multi-file datasets.
  intake_esm/source.py
  tests/sample-collections/cmip5-netcdf.csv
  tests/sample_data/cmip/cmip5/output1/NIMR-KMA/HadGEM2-AO/rcp85/mon/atmos/Amon/r1i1p1/v20130815/tasmax/tasmax_Amon_HadGEM2-AO_rcp85_r1i1p1_200511-200512.nc
  tests/test_source.py
Labels: enhancement

#409 Add Docs Based on ESDS Blog Posts
  ci/environment.yml
  docs/environment.yml
  docs/source/user-guide/ecgtools-history-files-example.ipynb
  docs/source/user-guide/graphviz_example.ipynb
  docs/source/user-guide/index.md
  docs/source/user-guide/intake-esm-derived-variables.ipynb
  docs/source/user-guide/intake_cmip6_debug.md
Labels: documentation

#412 Switch over to the furo theme
  docs/environment.yml
  docs/source/conf.py
Labels: documentation

#413 Reorganize docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  .pre-commit-config.yaml
  README.md
  ci/environment.yml
  docs/environment.yml
  docs/source/api.md
  docs/source/changelog.md
  docs/source/conf.py
  docs/source/explanation/esm-collection-spec.md
  docs/source/explanation/index.md
  docs/source/how-to/build-a-catalog-from-timeseries-files.md
  docs/source/how-to/define-and-use-derived-variable-registry.md
  docs/source/how-to/enforce-search-query-criteria-via-require-all-on.md
  docs/source/how-to/filter-catalog-by-substring-and-regex-criteria.md
  docs/source/how-to/index.md
  docs/source/how-to/install-intake-esm.md
  docs/source/how-to/manipulate-catalog.md
  docs/source/how-to/multi-variable-catalog.csv
  docs/source/how-to/multi-variable-collection.json
  docs/source/how-to/use-catalogs-with-assets-containing-multiple-variables.md
  docs/source/index.md
  docs/source/installation.md
  docs/source/reference/api.md
  docs/source/reference/changelog.md
  docs/source/reference/cmip_ap.md
  docs/source/reference/faq.md
  docs/source/reference/index.md
  docs/source/supplemental-guide/faq.md
  docs/source/tutorials/index.md
  docs/source/user-guide/cmip6-tutorial.ipynb
  docs/source/user-guide/ecgtools-history-files-example.ipynb
  docs/source/user-guide/graphviz_example.ipynb
  docs/source/user-guide/index.md
  docs/source/user-guide/intake-esm-derived-variables.ipynb
  docs/source/user-guide/intake_cmip6_debug.md
  docs/source/user-guide/manipulating-dataframe.ipynb
  docs/source/user-guide/multi-variable-assets.ipynb
  docs/source/user-guide/overview.ipynb
  docs/source/user-guide/search.ipynb
  intake_esm/cat.py
  intake_esm/core.py
  intake_esm/derived.py
  intake_esm/source.py
  tests/sample-collections/pangeo-gcp-subset.csv.gz
  tests/sample-collections/pangeo-gcp-subset.json
Labels: documentation

#417 Search returns same class as self - allowing subclassing
  intake_esm/core.py
  tests/test_core.py
Labels: enhancement

#421 Expose `pd.DataFrame.to_csv` and `json.dump` keyword arguments
  intake_esm/cat.py
  intake_esm/core.py
  tests/test_core.py
Labels: enhancement

#422 Pin importlib-metadata to 2.0
  .github/workflows/ci.yaml
Labels: maintenance

#429 Fix CI failures: don't turn warnings into errors
  .github/workflows/ci.yaml
  pyproject.toml
  setup.cfg
Labels: CI
