Repository intake/intake-esm, pull requests merged in 2021-08, with the labels that each got.

#349 Add cesm2-le catalog
  docs/source/catalogs.yaml
Labels: documentation

#347 Add pydantic models to facilitate data validation
  ci/environment-upstream-dev.yml
  ci/environment.yml
  intake_esm/_types.py
  requirements.txt
  setup.cfg
  tests/test_core.py
  tests/test_types.py
  tests/utils.py
Labels: enhancement, feature

#356 pin pandas version
  requirements.txt
Labels: dependencies
