Repository intake/intake-esm, pull requests merged in 2021-11, with the labels that each got.

#394 Properly check whether dataframe is empty
  intake_esm/cat.py
Labels: bug-fix

#399 Remove linting workflow: use pre-commit.ci
  .github/workflows/linting.yaml
Labels: internal-change

#403 Add `to_dask()` method to `esm_datastore`
  docs/source/user-guide/overview.ipynb
  intake_esm/core.py
  tests/test_core.py
Labels: feature

#408 Use mamba when building docs on Readthedocs
  readthedocs.yml
Labels: documentation

#405 Add to_collection method returning an Xcollection
  intake_esm/core.py
  requirements.txt
  tests/test_core.py
Labels: feature
