Repository intake/intake-esm, pull requests merged in 2022-03, with the labels that each got.

#454 Add tutorial module
  intake_esm/__init__.py
  intake_esm/tutorial.py
  tests/test_tutorial.py
  tutorial-catalogs/AWS-CESM2-LENS.json
  tutorial-catalogs/AWS-CMIP6.json
  tutorial-catalogs/GOOGLE-CMIP6.json
Labels: documentation, enhancement

#453 Ensure fsspec storage options are propagated to `xr.open_dataset`
  intake_esm/core.py
  intake_esm/source.py
  tests/test_source.py
Labels: bug-fix

#460 Change import to have configurable prefixes via `set_options`
  docs/source/reference/api.md
  intake_esm/__init__.py
  intake_esm/core.py
  intake_esm/source.py
  intake_esm/utils.py
  tests/test_core.py
Labels: enhancement

#464 updating google-cmip6 cat to have more datasets
  tutorial-catalogs/GOOGLE-CMIP6.json
Labels: documentation
