Repository intake/intake-esm, pull requests merged in 2022-08, with the labels that each got.

#508 ensure `storage_options` are passed to data loader
  intake_esm/core.py
Labels: bug-fix

#512 ENH: Add .to_datatree() method and remove to collection
  ci/environment-upstream-dev.yml
  ci/environment.yml
  docs/source/tutorials/index.md
  intake_esm/core.py
  requirements.txt
  tests/test_core.py
Labels: enhancement

#514 Discard `catalog_file` attribute after a search
  intake_esm/cat.py
  intake_esm/core.py
Labels: enhancement

#515 Add `keys_info()` method
  intake_esm/core.py
  tests/test_core.py
Labels: enhancement

#517 upgrade dependencies
  ci/environment-upstream-dev.yml
  ci/environment.yml
  docs/environment.yml
  requirements.txt
Labels: maintenance, CI
