Repository intake/intake-esm, pull requests merged in 2022-01, with the labels that each got.

#432 Fix dependency version conflict
  ci/environment-upstream-dev.yml
  ci/environment.yml
  requirements.txt
Labels: dependencies, CI

#400 Add Python 3.10 to CI
  .github/workflows/ci.yaml
  ci/environment-upstream-dev.yml
  ci/environment.yml
Labels: CI

#428 Improve search with derived variables
  intake_esm/core.py
  tests/test_core.py
Labels: bug-fix

#433 Add pyupgrade to pre-commit hooks
  .pre-commit-config.yaml
  docs/source/conf.py
  intake_esm/core.py
  intake_esm/utils.py
  tests/test_search.py
Labels: maintenance, CI
