Repository intake/intake-esm, pull requests merged in 2022-02, with the labels that each got.

#435 Support iterable columns with `require_all_on`
  intake_esm/_search.py
  intake_esm/cat.py
  tests/test_search.py
Labels: enhancement

#440 Remove unused `@df.setter`
  intake_esm/cat.py
Labels: bug-fix

#442 Add `last_updated` to the `ESMCatalogModel`
  intake_esm/cat.py
Labels: enhancement

#441 Derived Catalog: test for all needed variables and skip if existing
  intake_esm/derived.py
  tests/test_derived.py
Labels: enhancement

#446 Subset derived variable registry only with used derived variables
  intake_esm/core.py
  tests/test_core.py
Labels: enhancement, bug-fix
