Repository intake/intake-esm, pull requests merged in 2022-09, with the labels that each got.

#521 Reorganize the documentation
  ci/environment-docs.yml
  docs/source/conf.py
  docs/source/explanation/index.md
  docs/source/how-to/enforce-search-query-criteria-via-require-all-on.md
  docs/source/how-to/filter-catalog-by-substring-and-regex-criteria.md
  docs/source/how-to/index.md
  docs/source/how-to/manipulate-catalog.md
  docs/source/index.md
  docs/source/reference/esm-catalog-spec.md
  docs/source/reference/index.md
  docs/source/tutorials/loading-cmip6-data.md
  readthedocs.yml
Labels: documentation

#522 DOC: Add section on intake-esm keys
  docs/source/how-to/understand-keys-and-how-to-change-them.md
  docs/source/index.md
Labels: documentation

#523 Update how to guides
  docs/source/how-to/build-a-catalog-from-timeseries-files.md
  docs/source/how-to/define-and-use-derived-variable-registry.md
  docs/source/how-to/enforce-search-query-criteria-via-require-all-on.md
  docs/source/how-to/filter-catalog-by-substring-and-regex-criteria.md
  docs/source/how-to/manipulate-catalog.md
  docs/source/how-to/modify-catalog.md
  docs/source/how-to/understand-keys-and-how-to-change-them.md
  docs/source/how-to/use-catalogs-with-assets-containing-multiple-variables.md
  docs/source/index.md
Labels: documentation

#526 Check if all values in a groupby column are NaN or not NaN
  intake_esm/cat.py
  intake_esm/utils.py
Labels: bug-fix

#528 Update isort configuration to use `profile=black`
  setup.cfg
  tests/test_derived.py
Labels: maintenance
